- get_url: url='{{consul_url}}/consul_{{consul_version}}_linux_amd64.zip' dest=/tmp/consul.zip validate_certs=no

- group: name={{consul_group}}

- user: name={{consul_user}} group={{consul_group}}

- name: create consul dir
  file: path={{item}} state=directory owner={{consul_user}} group={{consul_group}}
  with_items:
    - '{{consul_dir}}'
    - '{{consul_dir}}/bin'
    - '{{consul_conf_dir}}'
    - '{{consul_data_dir}}'
    - '{{consul_log_dir}}'

- name: stop consul (in case it's running, else data folder will be locked)
  supervisorctl: name=consul state=stopped
  when: consul_supervisor_enabled and not ansible_os_family == 'Darwin'
  ignore_errors: yes

- name: copy over distro agnostic unpack script
  template: src=unpack dest=/tmp/unpack mode=755

- name: unpack the consul archive
  command: /tmp/unpack /tmp/consul.zip {{consul_dir}}/bin

- name: remove tmp consul zips
  file: path=/tmp/{{item}}.zip state=absent
  with_items:
    - consul

- name: make link to consul folder
  file: src='{{consul_dir}}' dest=/opt/consul state=link

- name: make consul executable
  file: path="{{consul_dir}}/bin/consul" mode=755

- name: make consul available on the path
  command: update-alternatives --install "/usr/bin/consul" "consul" "{{consul_dir}}/bin/consul" 100

- name: restart consul (in case it was just stopped)
  supervisorctl: name=consul state=restarted
  when: consul_supervisor_enabled and not ansible_os_family == 'Darwin'
